### ISSUE TITLE
Stickiness + shadow

### ISSUE THREAD

**Issue by Shyish** [MiguelCatalan/MaterialSearchView#11]
Hello!

First of all thanks for sharing this library, I was looking for something similar to use in my projects! :)

Currently I made a fork of it and I´m adding some personal changes that might be useful for you also, so I could make a PR if you´re interested:

* Stickiness: basically to stick it in the toolbar and remain there until dismissed (like Whatsapp search). This is useful if you don´t need suggestions (actually I´m thinking in enabling the "stickiness" when there are no suggestions) and you want to filter or to search the content directly in your layout.
* I could probably add some 9patch to the view so it has a shadow to fake the elevation in lower versions.

I hope you like the changes, I will create the PR soon so you can review/merge if you like them.

Cheers!

**Comment by MiguelCatalan** [comment]
Sounds good!
Hope to see you PR,

**Comment by Shyish** [comment]
Done! Hopefully I can add the shadow this weekend :)
