### ISSUE TITLE
Why is onQueryTextChange set to empty after clicking the search button?

### ISSUE THREAD

**Issue by zunjae** [MiguelCatalan/MaterialSearchView#112]
I love everything about this library, except for the fact that I do not understand WHY the variable "newText" is set to empty after clicking the submit button. It does not make any sense at all.

I wan to filter an adapter by calling a custom `filter(String string)` method inside the `onQueryTextChange` method provided by your library. It works until I press the enter button on my keyboard. After that it will clear the variable newText and as a result the filter will get cleared as well.

Current code

`@Override
            public boolean onQueryTextChange(String newText) {
                textFilter = newText;
                if (adapter != null) {
                    adapter.filter(textFilter);
                }
                return false;
            }`

Is there a way to fix this behavior?

**Comment by borjaruiz** [comment]
You have this method :

```
        public boolean onQueryTextSubmit(String query) {
            //Here you have the String after clicking submit button.            
            return false;
        }
```

**Comment by zunjae** [comment]
Yea but that method requires you to press the enter button and doesn't allow me to update my adapter in real time

**Comment by borjaruiz** [comment]
I don't get it at all, didn't you say "after clicking the submit button"? You can update your adapter in real time with the onQueryTextChange method and then, after submiting, with the onQueryTextSubtit.

**Comment by zunjae** [comment]
> You can update your adapter in real time with the onQueryTextChange method and then, after submiting, with the onQueryTextSubtit.

Woohoo, and there is where it goes wrong

`onQueryTextChange` is called BEFORE `onQueryTextSubmit`, which means that if you press the ENTER button on your keyboard, the `newText` variable will be set to `""` and so will it in `onQueryTextSubmit`.

Clicking enter clears the data you types, which means that the filter will get reset

**Comment by borjaruiz** [comment]
Yes, now I understand, maybe you can do some workaround with a local variable?

**Comment by borjaruiz** [comment]
ok @zunjae 
Solved with this. Try it!

```
searchView.setOnSearchViewListener(new MaterialSearchView.SearchViewListener() {
            @Override
            public void onSearchViewShown() {
                searchView.setOnQueryTextListener(new MaterialSearchView.OnQueryTextListener() {
                    @Override
                    public boolean onQueryTextSubmit(String query) {
                        Log.i(TAG,"textSubmit "+query);
                        searchView.setOnQueryTextListener(null);
                        return false;
                    }

                    @Override
                    public boolean onQueryTextChange(String newText) {
                        if(searchView.isSearchOpen())
                            Log.i(TAG,"textChange "+newText);

                        return false;
                    }
                });
            }

            @Override
            public void onSearchViewClosed() {

            }
        });
```

**Comment by zunjae** [comment]
That worked, thanks a lot!
