### ISSUE TITLE
Could you explain how you had achieved background shadowing effect?

### ISSUE THREAD

**Issue by WINTEX** [MiguelCatalan/MaterialSearchView#120]
I'm really new to android and almost made this library to work, the problem is, i had not achieved the shadowing effect, and don't know how to do it. I tried everything, even string-by-streang examined your sample, but i had not found any solution.
![voice 1](https://cloud.githubusercontent.com/assets/17519112/19411494/6d2581c4-930b-11e6-807f-23e06fd1a593.gif)
![opekn_ervxq 1](https://cloud.githubusercontent.com/assets/17519112/19411512/bb4f1630-930b-11e6-93f2-d9aa0d342e91.jpg)

**Comment by WINTEX** [comment]
Added suggestions, its shadows now, but background dissapeared.
![fjtxbx6sr2s 1](https://cloud.githubusercontent.com/assets/17519112/19411673/9fb1f084-930e-11e6-84ef-9a8970146b02.jpg)

**Comment by WINTEX** [comment]
Not need that anymore :)

**Comment by droid-wise** [comment]
How did you achive this?

**Comment by WINTEX** [comment]
Could you be a little more specific please, what "this"?

**Comment by cristian1703** [comment]
@WINTEX  By this he means how did you achieve the shadowing effect. It might be useful to post some code as example. For example my content gets hidden as well
