### ISSUE TITLE
SearchView not displayed.

### ISSUE THREAD

**Issue by Chefty** [MiguelCatalan/MaterialSearchView#143]
Hello,

It looks like the searchview dont want to show up over the toolbar.
My main activity XML dont allow me to put the toolbar inside a framelayout, maybe it is the problem ?
Here is my activity_main.xml:

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/main_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    android:gravity="center">

    <android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        android:elevation="4dp"
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
        app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />

    <com.miguelcatalan.materialsearchview.MaterialSearchView
        android:id="@+id/searchView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

    
    <FrameLayout
        android:id="@+id/drawer_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@id/toolbar">

        
        <FrameLayout
            android:id="@+id/frame_container"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <include layout="@layout/activity_home" />

        </FrameLayout>
    </FrameLayout>
</RelativeLayout>

Thank you in advance, 

Chefty.

**Comment by carmas123** [comment]
+1

**Comment by Chefty** [comment]
I finally resolved it.

I just had to delete the _android:elevation_ parameter from the toolbar xml.

**Comment by QADOOMI** [comment]
Plus you can add elevation to the search view.
