### ISSUE TITLE
MaterialSearchView not closing on back button press.

### ISSUE THREAD

**Issue by fermatijoe** [MiguelCatalan/MaterialSearchView#163]
This is the code

    @Override
    public void onBackPressed() {
        DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout);
        if (drawer.isDrawerOpen(GravityCompat.START)) {
            drawer.closeDrawer(GravityCompat.START);
        } else {
            super.onBackPressed();
        }
        if (mMaterialSearchView.isSearchOpen()) {
            mMaterialSearchView.closeSearch();
            mMaterialSearchView.setVisibility(View.GONE);
        } else {
            super.onBackPressed();
            mMaterialSearchView.setVisibility(View.GONE);
        }
    }

If i press the back button just the keyboard closes and the searchView remains open. If i press again the button the app closes.

**Comment by ozv101** [comment]
This works for me
```
if(materialSearchView.isSearchOpen()) {
    materialSearchView.closeSearch();
}
```

**Comment by ozv101** [comment]
Are you sure `super.onBackPressed();` isn't being called in your first if/else statement before it gets to the next one?

**Comment by fermatijoe** [comment]
Yes sorry it was a total overlook on my part.
