### ISSUE TITLE
Search history

### ISSUE THREAD

**Issue by lduparc** [MiguelCatalan/MaterialSearchView#17]
Hi, 

I would like to have more information about your provider. I'm trying to implement a custom provider in order to manage an history. 

For now I'm just using your SearchAdapter to be able to add suggestions but if I restart the application I lost them. I would like to manage my own provider in order to save my queries but I was not able to add a provider and an xml with searchable config.

I don't understand why the application told me that you already have a provider.

Can you give me more information ?

**Comment by MiguelCatalan** [comment]
Sorry @lduparc I'm moving to a new job in other city and I am too busy at the moment.

Did you find what you were looking for?
