### ISSUE TITLE
 java.lang.IllegalStateException: Cannot start this animator on a detached view!

### ISSUE THREAD

**Issue by mrzslr** [MiguelCatalan/MaterialSearchView#172]
hi, first of all i added MaterialSearchView in fragment . i wanna call showSearch method in onCreateView when fragment attached or opened , but i got faced with this exception . 
i try many tricks to handle this problem but i didn't . help me in.

**Comment by mrzslr** [comment]
I try many ways to solve this but I couldn't.but I found a way to handle this since this way is not fine.
I show material search view just after a delay by this code in onCreateView method ( for fragments ).
```
 Handler handler = new Handler();
        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                materialSearchView.showSearch();
            }
        },100);
        return v;
```

**Comment by lukaskris** [comment]
thanks for help 👍

**Comment by DenisMakovskyi** [comment]
`@UiThread
public void openSearchView() {
    vSearch.showSearch();
}`

**Comment by tinkooladik** [comment]
it's enough to do it when the view was rendered, no delay is needed
```
new Handler().post(() -> mSearchView.showSearch());
````
