### ISSUE TITLE
Usage with TabLayout and AppBarLayout

### ISSUE THREAD

**Issue by Songroid** [MiguelCatalan/MaterialSearchView#18]
I'm using the MaterialSearchView with TabLayout, AppBarLayout and RecyclerView. The toolbar is hidden when the list is scrolling. I tried the following layouts:

A. The search view is below tabs:
```
AppBarLayout
  ToolBar
  TabLayout
  MaterialSearchView
/AppBarLayout
```
B. The toolbar scrolling doesn't work anymore: 
```
AppBarLayout
  FrameLayout  
    ToolBar
    MaterialSearchView
  /FrameLayout  
  TabLayout
/AppBarLayout
```

What I expect is the effect like the "My apps" section in the Play Store app. The search view is actually placed above the activity though. Any suggestions?

**Comment by MiguelCatalan** [comment]
Sorry for the delay, :sweat:

I'm curretly moving to a new job. I will check it asap.

**Comment by therajanmaurya** [comment]
I have solved like that problem using MaterialSearchView Library.

In my case I have Design Support Navigation Drawer and in activity_main i have FrameLayout for Transition of different Fragment and i am not setting my Toolbar in activity_main , i am setting it into Fragment Xml.

My activity_main xml is 
    <?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/drawer_layout"
    android:layout_height="match_parent"
    android:layout_width="match_parent"
    android:fitsSystemWindows="true">

    <LinearLayout xmlns:android = "http://schemas.android.com/apk/res/android"
        android:layout_width = "match_parent"
        android:layout_height = "match_parent"
        android:orientation = "vertical">

        <com.miguelcatalan.materialsearchview.MaterialSearchView
            android:id="@+id/search_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            style="@style/MaterialSearchViewStyle"/>

        <FrameLayout
            android:id = "@+id/frame_container"
            android:layout_width = "match_parent"
            android:layout_height = "0dp"
            android:layout_weight = "1"/>

    </LinearLayout>

    <android.support.design.widget.NavigationView
        android:id="@+id/nav_view"
        android:layout_height="match_parent"
        android:layout_width="wrap_content"
        android:layout_gravity="start"
        android:fitsSystemWindows="true"
        app:headerLayout="@layout/navigation_header"
        app:menu="@menu/navigation_list_menu">

	    </android.support.design.widget.NavigationView>

</android.support.v4.widget.DrawerLayout>

and setting all the Java things in MainActivity as mention on github page

**Comment by Songroid** [comment]
@therajanmaurya Thanks for your answer. Are you implementing your AppBarLayout, TabLayout and ViewPager all in a fragment? Then use that fragment to contain all sub-fragments?

**Comment by hahmadbilal** [comment]
Hi i  have same issue. my layout structure are:
Coordinate
   Appbar
     FramLayout
       ToolBar
       MaterialSearchView
    </FrameLayout>
    TabLayout
  Appbar
 ViewPager
CoordianteLayout

**Comment by progfiles** [comment]
Same trouble same layout

**Comment by MiguelCatalan** [comment]
I've already "fixed" it. 

Well, actually I added and example of how to implemented it. I will release a new versión in the next two days at most.

**Comment by progfiles** [comment]
Hi! Whaiting for your update =)

**Comment by tajchert** [comment]
@MiguelCatalan can you commit your fix? I have same problem.

**Comment by MiguelCatalan** [comment]
Check out the [readme](https://github.com/MiguelCatalan/MaterialSearchView#using-appbarlayout)

**Comment by pro100svitlo** [comment]
@MiguelCatalan 
Hi again )
maybe I am doing something wrong, but your advance doesn't help me. here is how my xml looks now:
http://pastebin.com/4dGzC85A

**Comment by Songroid** [comment]
It seems that the scrollable toolbar doesn't work with the library. For example,
<android.support.v7.widget.Toolbar
    android:id="@+id/toolbar"
    android:layout_width="match_parent"
    android:layout_height="?attr/actionBarSize"
    android:background="?attr/colorPrimary"
    app:layout_scrollFlags="scroll|enterAlways" />
the app:layout_scrollFlags part is not working. 
Reference: https://mzgreen.github.io/2015/06/23/How-to-hideshow-Toolbar-when-list-is-scrolling(part3)/

**Comment by pro100svitlo** [comment]
@Songroid I tried this,
clear app:layout_scrollFlags.
 but my problem is still haven't been solved.

**Comment by Songroid** [comment]
@pro100svitlo Mine is working fine. Is there any screenshot available?

**Comment by pro100svitlo** [comment]
sure!
here is screenshot after search icon was clicked
![screenshot_20160112-214215](https://cloud.githubusercontent.com/assets/12133914/12274961/11213a0e-b976-11e5-8aa3-9b7b57ae6f5d.png)

**Comment by pro100svitlo** [comment]
@Songroid it looks like it is just doesn't show any changes after click...
maybe i am missing something inside xml code.... 
did you saw this http://pastebin.com/4dGzC85A ??

**Comment by Jock69pl** [comment]
This same problem. CoordinatorLayout made this bug. But without it TextEdit field isn't visible.

**Comment by MiguelCatalan** [comment]
Take a look in the native approach: http://www.materialdoc.com/search-filter/

**Comment by kal4l** [comment]
@pro100svitlo 
I had the same issue; I was able to get the search bar to show by adding this to the search view listener (Manually set the seach view to visible):

``` java
searchView.setOnSearchViewListener(new MaterialSearchView.SearchViewListener() 
{
      @Override
      public void onSearchViewShown() {
          searchView.setVisibility(View.VISIBLE);
          Log.i(TAG, "Showing Search View!");
      }
...
```

**Comment by martellux** [comment]
Hello Miguel, hello everybody,

I've just cloned the project and the I'm still facing the problem, i.e. the search view not showing on click, when I use the MaterialSearchView together with AppBarLayout, CoordinatorLayout, TabLayout and ViewPager.
The trick in the documentation, i.e. putting the MaterialSearchView visibility to gone, doesn't help. Nothing's changed.

I made a little debug and I found out that using the TabLayout avoids to MaterialDesignView to be measured correctly (at this point really curious to understand how visibility to gone could fix it) so I've fix it using TreeObserver.
I've reverted the visibility to visibile on the layout and I've added a OnPreDrawListener to the view's TreeObserver in order to both let the view being measured correctly and put its visibility to gone before being drawn.

That's it.

**Comment by ghost** [comment]
I had the same problem
@kevcgrant  solution should fix it
Thanks dude

**Comment by teepipe** [comment]
Still not working. 

Even the sample code does not work, tried after clone. 

On click on search button, the search box is not opened, but keyword does. setting in on onSearchViewShown function by setting visibility, does open the list but then the fragment and list behind are completely hidden.

![1](https://cloud.githubusercontent.com/assets/20532442/21449873/97a3ed40-c917-11e6-9e13-e42502c86065.jpg)

![2](https://cloud.githubusercontent.com/assets/20532442/21449868/8b3cfa2e-c917-11e6-9f63-2bc0b5a3182b.jpg)
