### ISSUE TITLE
Voice is invalid

### ISSUE THREAD

**Issue by guoyoujin** [MiguelCatalan/MaterialSearchView#19]
Voice voice is invalid, the right ICONS don't show this is why, I have realized the following code

        searchView.setVoiceSearch(true);

**Comment by MiguelCatalan** [comment]
I don't really understand you. :confused:
Can you explain yourself a little better please?

**Comment by tridangky** [comment]
When I create a new project with android studio and then do all steps in your tutorial but cannot open google voice windows. But I can use google voice search in your downloaded sample.
