### ISSUE TITLE
Maybe some animation when the search bar is closed by pressing the back button?

### ISSUE THREAD

**Issue by TonyTangAndroid** [MiguelCatalan/MaterialSearchView#24]
By far, this is the best repository of Material search view. There might be some enhancement on closing the search bar. It will be more natural if some animation is added.

**Comment by MiguelCatalan** [comment]
Added

**Comment by broakenmedia** [comment]
I would like to see this too! Currently tapping the back button on the search view just instantly closes the search box

**Comment by Yelamanmyrzahanov** [comment]
@MiguelCatalan can you share a gist of Animation code please? It would be very helpful for me
