### ISSUE TITLE
Icon in front of suggestions: Is this customizable?

### ISSUE THREAD

**Issue by Rainer-Lang** [MiguelCatalan/MaterialSearchView#25]

**Comment by MiguelCatalan** [comment]
Next time check the readme please.


        <item name="searchSuggestionIcon">@drawable/ic_suggestion</item>

**Comment by Rainer-Lang** [comment]
But this is general - not for each separate?
My suggestions come from different sources and I want to visualize this for the user.

**Comment by MiguelCatalan** [comment]
Oh, I see. :sweat_smile:

You can implement your own adapter. 

https://github.com/MiguelCatalan/MaterialSearchView/blob/develop/library/src/main/java/com/miguelcatalan/materialsearchview/SearchAdapter.java

**Comment by Rainer-Lang** [comment]
Thanks.
