### ISSUE TITLE
Maven repo

### ISSUE THREAD

**Issue by guyferguson** [MiguelCatalan/MaterialSearchView#251]
Hi,
Are there any plans to migrate 1.4.0 to Maven?  Have I missed a discussion somewhere?  I cannot release an app that uses the cute Material SearchView because google won't accept libraries on jcenter() any longer.

Is there a simple fix for this?

**Comment by moetouban** [comment]
looks like the library has been abandoned by contributors (5 years ago)

**Comment by moetouban** [comment]
@MiguelCatalan @lgvalle ^^

**Comment by lgvalle** [comment]
@guyferguson you should not use this library. As @moetouban said it's not been updated in 5+ years. There should be other more updated alternatives out there

**Comment by guyferguson** [comment]
Thanks all for your responses.  I will look for an alternative.  I picked it up via cloning another repo ( https://github.com/c0de-wizard/android-liveData-viewModel) and hadn't realised how old it was.
