### ISSUE TITLE
Allow Submit query text without trigger query changes

### ISSUE THREAD

**Issue by ffgiraldez** [MiguelCatalan/MaterialSearchView#31]
I have the use case, that when filling the suggestion list using values that come from ```OnQueryTextListener``` when user click on a suggestion i want to trigger a full search, like Google Play and other apps using
```java
 searchView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
     @Override
     public void onItemClick(AdapterView<?> parent, View view, int position, long id) {         
         searchView.setQuery(suggestion, true);
     }
 });
```
but with this trigger an ```OnQueryTextListener.onQueryTextChange()``` before ```OnQueryTextListener.onQueryTextSubmit()``` and that trigger is unnecessary in mostly cases

Digging in the code i see the function ```onSubmitQuery();``` just allowing a String as parameter and provide a public method ```submitQuery(String query)``` that call ```onSubmitQuery``` internally that not trigger ```OnQueryTextListener.onQueryTextChange()``` solve the problem.

I could do it, but first i want to know your opinion.

**Comment by bluedoctorhazan** [comment]
searchView.setSubmitOnClick(true);

**Comment by MiguelCatalan** [comment]
Wow, I totally missed this issue, sorry @ffgiraldez .

As @phamvansy posted, you can do this from last update by:

``` java
searchView.setSubmitOnClick(true);
```
