### ISSUE TITLE
problem with lollipop and above

### ISSUE THREAD

**Issue by pro100svitlo** [MiguelCatalan/MaterialSearchView#36]
Hi!
good library, thanks for it!
but i got some problem with devices with lollipop and above.
when i am clicking on search icon the keyboard is open, search is working. but...
ordinary title is showing and edit text doesn't show...
try this problem on few devices with lollipop

**Comment by mradzinski** [comment]
We tested this on Marshmallow, Lollipop and Kitkat devices without any issue. Would you mind including your layout and code you're using? Sounds like some kind of layout issue to me.

**Comment by pro100svitlo** [comment]
sure I can :)

here is xml code:
`<android.support.design.widget.AppBarLayout
        android:id="@+id/appBar_contacts"
        android:layout_height="wrap_content"
        android:layout_width="match_parent"
        android:theme="@style/AppTheme.AppBarOverlay"
        android:animateLayoutChanges="true"
        android:fitsSystemWindows="true" >
        <FrameLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:layout_scrollFlags="scroll|enterAlways"
            >
            <android.support.v7.widget.Toolbar
                android:id="@+id/toolbar_contacts"
                style="@style/SU_ToolBar"
                />
            <com.miguelcatalan.materialsearchview.MaterialSearchView
                android:id="@+id/msv_contacts"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                style="@style/SU_MaterialSearchView"
                />
        </FrameLayout>
        <android.support.design.widget.TabLayout
            android:id="@+id/tl_contacts"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@color/su_primary"
            app:tabIndicatorColor="@color/su_accent_color"
            app:tabMode="fixed"
            app:tabGravity="fill"/>

    </android.support.design.widget.AppBarLayout>`

and here is code inside fragment:
```@Override
    public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
        super.onCreateOptionsMenu(menu, inflater);
        getActivity().getMenuInflater().inflate(R.menu.menu_contacts, menu);

        MenuItem item = menu.findItem(R.id.action_search);
        mSearchView.setMenuItem(item);
    }

private void setSearchMenuListener(){
        mSearchView.setOnQueryTextListener(new MaterialSearchView.OnQueryTextListener() {
            @Override
            public boolean onQueryTextSubmit(String query) {
                return false;
            }

            @Override
            public boolean onQueryTextChange(String newText) {
                if (newText.length() > 0) {
                    newText = newText.substring(0, 1).toUpperCase() + newText.substring(1, newText.length());
                }
                showSearchQuery(newText);
                return false;
            }
        });

        mSearchView.setOnSearchViewListener(new MaterialSearchView.SearchViewListener() {
            @Override
            public void onSearchViewShown() {
            }

            @Override
            public void onSearchViewClosed() {
            }
        });
    }
```

maybe i miss something?

**Comment by MiguelCatalan** [comment]
It is related with AppBarLayout issue. Already reported in #18

**Comment by pro100svitlo** [comment]
@MiguelCatalan , I am sorry, but I cant find solution there. where did you post answer on issue#18?

**Comment by MiguelCatalan** [comment]
@pro100svitlo Not yet sorry. Christmas and urgent tasks at work didn't let me. I promise I'll do asap. I hope it will this week.

**Comment by pro100svitlo** [comment]
Thanks, but don't worry ) 
It is New Year holidays, so add some magic into your life :) 
Happy new year and merry Christmas ;-)

**Comment by NhocKun** [comment]
hi everybody,
i have same issues, i don't using AppBarLayout. Here my xml code:

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/layoutMain"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <include
        android:id="@+id/toolbar_actionbar"
        layout="@layout/toolbar_default"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

    <android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/drawer"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@+id/toolbar_actionbar">

        <FrameLayout
            android:id="@+id/container"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:clickable="true" />

        
        <fragment
            android:id="@+id/fragment_drawer"
            android:name="NavigationDrawerFragment"
            android:layout_width="@dimen/navigation_drawer_width"
            android:layout_height="match_parent"
            android:layout_gravity="start"
            app:layout="@layout/fragment_navigation_drawer"
            tools:layout="@layout/fragment_navigation_drawer" />
    </android.support.v4.widget.DrawerLayout>

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <com.miguelcatalan.materialsearchview.MaterialSearchView
            android:id="@+id/search_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />
    </FrameLayout>

</RelativeLayout>

What is wrong here? Please fix this. Thanks!

**Comment by Alxzu** [comment]
Hi, I was getting the same problem with my nexus 7. Finally the problem was in my toolbar's xml with the elevation

```
<!-- Toolbar -->
        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            app:layout_scrollFlags="scroll|enterAlways"
            app:popupTheme="@style/ThemeOverlay.AppCompat.Light"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary"
            android:elevation="@dimen/default_elevation"
            android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar" />
```

Removing elevation property I managed to make it work, Thanks 4 this library

**Comment by A86S** [comment]
When I run your sample example of tab activity the same issue occurs with Nexus 5 (Marshmallow)

**Comment by ghost** [comment]
@kevgrant solution

```
searchView.setOnSearchViewListener(new MaterialSearchView.SearchViewListener() 
{
      @Override
      public void onSearchViewShown() {
          searchView.setVisibility(View.VISIBLE);
          Log.i(TAG, "Showing Search View!");
      }
...
```

**Comment by meridaaa** [comment]
Hi I am using it exactly like tutorial but it is not shown on the app! I changed it a lot.
Can anybody help me?
@MiguelCatalan 
Here is the code :
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/container"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#bdbdbd">

    <ProgressBar
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/connect_progress"
        android:visibility="gone"
        android:layout_centerHorizontal="true"
        android:layout_centerVertical="true"
        tools:layout_editor_absoluteY="0dp"
        tools:layout_editor_absoluteX="0dp" />

    <Button
        android:layout_width="368dp"
        android:layout_height="495dp"
        android:id="@+id/net_connect"
        android:background="@color/fbutton_color_transparent"
        android:layout_below="@+id/toolbar_container" />

    <android.support.v7.widget.RecyclerView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/rcyclview"
        android:scrollbars="vertical"
        android:background="#e0e0e0"
        tools:layout_editor_absoluteY="8dp"
        tools:layout_editor_absoluteX="8dp"
        android:layout_below="@+id/toolbar_container"
        />

    <RelativeLayout
        android:id="@+id/toolbar_container"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="@color/colorPrimary" />

        <com.miguelcatalan.materialsearchview.MaterialSearchView
            android:id="@+id/search_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />
    </RelativeLayout>

    </RelativeLayout>

  searchView = (MaterialSearchView) view.findViewById(R.id.search_view);
        searchView.setOnQueryTextListener(new MaterialSearchView.OnQueryTextListener() {
            @Override
            public boolean onQueryTextSubmit(String query) {
                //Do some magic
                return false;
            }

            @Override
            public boolean onQueryTextChange(String newText) {
                //Do some magic
                return false;
            }
        });

        searchView.setOnSearchViewListener(new MaterialSearchView.SearchViewListener() {
            @Override
            public void onSearchViewShown() {
                searchView.setVisibility(View.VISIBLE);
                //Do some magic
            }

            @Override
            public void onSearchViewClosed() {
                //Do some magic
            }
        });

    @Override
    public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
        super.onCreateOptionsMenu(menu, inflater);
        inflater.inflate(R.menu.menu_main2, menu);
        MenuItem item = menu.findItem(R.id.action_search);
        searchView.setMenuItem(item);
        return;

    }

**Comment by javadkia** [comment]
@kevgrant solution work for me, thanks @smidaharoun
``   @Override
      public void onSearchViewShown() {
          searchView.setVisibility(View.VISIBLE);
}``
