### ISSUE TITLE
In TabActivity,setSuggestions will make searchview fullscreen,activity is not visible. 

### ISSUE THREAD

**Issue by fg607** [MiguelCatalan/MaterialSearchView#44]
Thanks the good library.

It will make activity or fragment invisible,after use setSuggestions method.

I have seen the pictures shown in the README.md ,and the activity is visible when show  suggestions.

I need your help ,thanks.

**Comment by MiguelCatalan** [comment]
Can you show your implementation?

**Comment by fg607** [comment]
Thanks your reply,i have found the problem,it's really my question. 
I have put MaterialSearchView into AppBarLayout, so the entire screen is filled by the appbar.
Good library,Thanks again.
