### ISSUE TITLE
How can I implement your SearchView in Fragment ?

### ISSUE THREAD

**Issue by StevenWatremez** [MiguelCatalan/MaterialSearchView#45]
Have you an exemple of your SearchView in a Fragment ? I need to use a fragment with your SearchView.

**Comment by StevenWatremez** [comment]
Inside an activity, your lib works, but not inside a fragment. You have an idea why ?

**Comment by StevenWatremez** [comment]
Nobody can help me ?

**Comment by StevenWatremez** [comment]
If my question is obvious, can you answer me ?

**Comment by goraga1** [comment]
In your fragment 
setHasOptionsMenu(true);

```
@Override
public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
    inflater.inflate(R.menu.search_view, menu);
    super.onCreateOptionsMenu(menu, inflater);
    final MenuItem item = menu.findItem(R.id.action_search);
    searchView.setMenuItem(item);
```

}

**Comment by lancevalour** [comment]
You have to set support action bar for the parent activity in your fragment.

**Comment by omarhammad** [comment]
<menu xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    tools:context="com.abdallahmurad.sqlite001.MainActivity">
    <item
        android:id="@+id/action_search"
        android:icon="@drawable/ic_search"
        android:title="@string/search"
        app:showAsAction="always"
        />
</menu>
