### ISSUE TITLE
Any way to download jar/aar?

### ISSUE THREAD

**Issue by Songroid** [MiguelCatalan/MaterialSearchView#46]
My company has a build server without Internet access. Any 3rd-party library needs to be uploaded separately. I've searched Maven but I couldn't find it. Where and how can I download the jar/aar file of your library?

**Comment by MiguelCatalan** [comment]
Try here https://dl.bintray.com/miguelcatalan/maven/com/miguelcatalan/materialsearchview/1.3.1/

**Comment by Songroid** [comment]
Cool! For the future version, it's the same link with the version change, right?

**Comment by MiguelCatalan** [comment]
Yep! I will add it to the README. :bowtie:
