### ISSUE TITLE
Request: let MaterialSearchView to be viewed even in UI-editor preview window

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [MiguelCatalan/MaterialSearchView#48]
it has NPE:

java.lang.NullPointerException   at com.miguelcatalan.materialsearchview.MaterialSearchView.isVoiceAvailable(MaterialSearchView.java:270)   at com.miguelcatalan.materialsearchview.MaterialSearchView.showVoice(MaterialSearchView.java:444)   at

**Comment by MiguelCatalan** [comment]
Can you fix it and send a PR?

**Comment by AndroidDeveloperLB** [comment]
If you are talking about pull-request, I never did it because I don't know how.
However, here's the fix:
in MaterialSearchView.java file, in the function of "isVoiceAvailable" add this as the first lines of code: 

        if (isInEditMode())
            return true;

This will prevent the preview window from show errors.

**Comment by AndroidDeveloperLB** [comment]
Also, please let me know how to trigger the sticky behavior of the MaterialSearchView (written about it here: https://github.com/MiguelCatalan/MaterialSearchView/issues/43 ) . I keep searching why it doesn't work for me , and can't find out.
I think this can be changed by adding a flag for "showKeyboard": 

           imm.showSoftInput(view, InputMethodManager.HIDE_IMPLICIT_ONLY);

But I'm not sure.

I've also found another issue: The tab example doesn't show the EditText of the MaterialSearchView

**Comment by MiguelCatalan** [comment]
@AndroidDeveloperLB Please don't mix the issues. 

Write about #43 in #43, please

**Comment by MiguelCatalan** [comment]
FYI you can follow this instructions to learn how to do a PR http://stackoverflow.com/a/14681796

**Comment by AndroidDeveloperLB** [comment]
sorry and thank you. I'm just stuck on this issue and i really need help.

**Comment by MiguelCatalan** [comment]
Why are you stuck? preview shouldn't block the workflow

BTW, thanks for the tip

**Comment by AndroidDeveloperLB** [comment]
Not on this issue.  :)
Issue 43...

**Comment by AndroidDeveloperLB** [comment]
About PR, I don't understand how to do it. After forking, and editing the code, what should I click? How could it be that it has so many steps?

**Comment by AndroidDeveloperLB** [comment]
Do you need the PR ?

**Comment by MiguelCatalan** [comment]
Would be nice.

The workflow is:
- Fork
- Create a branch for the PR (like fix_nullpointer_preview_editor)
- Edit the code
- Commit
- Push to your remote
- Create the PR with this: https://help.github.com/articles/creating-a-pull-request/

**Comment by AndroidDeveloperLB** [comment]
I've created it here:
https://github.com/MiguelCatalan/MaterialSearchView/pull/49
but I don't understand what to do now.
Do you see it?
BTW, the tab sample still doesn't work

**Comment by MiguelCatalan** [comment]
Yep, I will check it.

Thanks!

**Comment by AndroidDeveloperLB** [comment]
Do i need to do anything with the fork? What happens to the fork when you update the code with other stuff? I'm quite new with this... I only created repos and used others. Never did something in between...

Also, i have an issue with the app I'm working on, not being able to use the new version via the dependency, yet the sample app works fine even when I change it to :

compile 'com.miguelcatalan:materialsearchview:1.3.1'

Changing back to 1.3.0 works. Do you know why, perhaps?

**Comment by MiguelCatalan** [comment]
I will need to review it.

You can use your own repo if you want. After de PR are accepted or not, doesn't affect to yours. Yoy can delete it.

**Comment by AndroidDeveloperLB** [comment]
What if I delete it now?
Also, do you know why i have issues with 1.3.1 ?
