### ISSUE TITLE
uses-sdk:minSdkVersion 14 cannot be smaller than version 16

### ISSUE THREAD

**Issue by AngleV** [MiguelCatalan/MaterialSearchView#5]

**Comment by MiguelCatalan** [comment]
Why?

**Comment by AngleV** [comment]
@MiguelCatalan 
Because my project has minSdkVersion = 14

One work around is to place 

<uses-sdk tools:overrideLibrary="com.miguelcatalan.materialsearchview"/>
inside Manifest file.

**Comment by MiguelCatalan** [comment]
Oh sorry I misunderstood you, this is fixed already and would be available in the next release, probably in a few minutes.

**Comment by AngleV** [comment]
@MiguelCatalan you rock !

**Comment by MiguelCatalan** [comment]
Deployed!
