### ISSUE TITLE
setOnSuggestionListener is abailable??

### ISSUE THREAD

**Issue by Spiderbezno** [MiguelCatalan/MaterialSearchView#54]
Hi,

how i Can click an element of suggestion array?? In the original searview ther is the method setOnSuggestionListener

THX

**Comment by MiguelCatalan** [comment]
Check the [README](https://github.com/MiguelCatalan/MaterialSearchView/blob/develop/README.md)
```java
searchView.setOnQueryTextListener(new MaterialSearchView.OnQueryTextListener() {
            @Override
            public boolean onQueryTextSubmit(String query) {
                //Do some magic
                return false;
            }

            @Override
            public boolean onQueryTextChange(String newText) {
                //Do some magic
                return false;
            }
        });
```

**Comment by Spiderbezno** [comment]
But this methos ara for query acctions, butt if i want listener the click of a element of suggestion array are the same methods??

**Comment by MiguelCatalan** [comment]
Not at the moment.

Can I ask in which scenario do you need that?

**Comment by Spiderbezno** [comment]
FOr example Im a serach for a EPG and I write 2 o more characters, a suggestion box appear with the possible results(obteined form a server request) and you can click in one of this resukts to see the detaisl in other activity

**Comment by Spiderbezno** [comment]
Similr at the methos at native os searchview

**Comment by MiguelCatalan** [comment]
Totally true.

Can you send a PR with the implementation?

**Comment by Spiderbezno** [comment]
The solution could be something like that
mSearchView.setOnSuggestionListener(new SearchView.OnSuggestionListener() {
                @Override
                public boolean onSuggestionSelect(int position) {
                    return false;
                }

                @Override
                public boolean onSuggestionClick(int position) {
                    mSearchView.setQuery(suggestions.get(position).getName(), false);
                    mSearchView.clearFocus();
                    HLimitedProgram[] epgSearchList = new HLimitedProgram[1];
                    epgSearchList[0] = suggestions.get(position);
                    Intent intent = new Intent(getBaseContext().getApplicationContext(), EPGListSearch.class);
                    intent.putExtra("userConsulta", userConsulta);
                    intent.putExtra("resultSearch", epgSearchList);
                    ActivityOptionsCompat options = ActivityOptionsCompat.makeCustomAnimation(TelevisionActivity.this, android.R.anim.slide_in_left, android.R.anim.slide_out_right);
                    ActivityCompat.startActivity(TelevisionActivity.this, intent, options.toBundle());
                    return true;
                }
            });

**Comment by joydeepsaha05** [comment]
This is how I did it:
```javascript
searchView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                String query= (String) parent.getItemAtPosition(position);
                loadData(query);
                searchView.closeSearch();
            }
});

public void loadData(final String query) {
    //magic here!
}
```

**Comment by Spiderbezno** [comment]
This is a goog option @joydeepsaha05 thx

**Comment by rana01645** [comment]
After setting the searchView.searchSuggestion call searchView.setOnItemClickListener

Example:

searchView.setSuggestions(sugarray);`
searchView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
@override
public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
String query = (String) parent.getItemAtPosition(position);
searchView.closeSearch();
}
});

**Comment by ihewro** [comment]
> ```js
> String query= (String) parent.getItemAtPosition(position);
>                 loadData(query);
>                 searchView.closeSearch();
> ```

thx!

**Comment by basilabraham44** [comment]
@rana01645  thank you
