### ISSUE TITLE
searchview inside Fragment is null

### ISSUE THREAD

**Issue by AngleV** [MiguelCatalan/MaterialSearchView#6]
i am using your library but i use fragments.
So i do not inflate main menu in activity but inside fragment.
How to obtain reference to searchview ?

i tried
 searchView = (MaterialSearchView)findViewById(R.id.search_view); but it returns null

**Comment by MiguelCatalan** [comment]
I can't test it right now, I will in a few hours.

Meanwhile try this http://stackoverflow.com/a/15654039/1994530

**Comment by AngleV** [comment]
ok but in fragment where to call        
searchView = (MaterialSearchView) findViewById(R.id.search_view);

**Comment by AngleV** [comment]
Figure it out
inside fragment onCreateOptionsMenu you call 

final MaterialSearchView searchView = (MaterialSearchView) getActivity().findViewById(R.id.search_view);

**Comment by MiguelCatalan** [comment]
Cool!

**Comment by ravigupta9363** [comment]
@AngleV  I am unable to use this library inside fragment, as it is showing `class not initiated` error, can you help me

**Comment by samy-baili** [comment]
I have the same issue, someone found a solution ?

**Comment by Maikol1804** [comment]
Hi, I am using your library but I don't know if is possible pass a value linked with the text to setSuggestions(), currently this method has one parameter that is the text, but if I want to manage that text with a specific value, what could I do?. Happens that in my case some suggestions are same.
