### ISSUE TITLE
searchView.setVoiceSearch(true); //or false dosn

### ISSUE THREAD

**Issue by Adnan9011** [MiguelCatalan/MaterialSearchView#60]
setVoiceSearch dosn't declar in this source code . please check this .

my code is :
searchView = (MaterialSearchView) findViewById(R.id.search_view);
        searchView.showVoice(false);
        searchView.setVoiceSearch(true); //or false // Error
        searchView.setOnQuery.....

**Comment by Adnan9011** [comment]
i found solution , in repo in maven when add library with gradle it works, but when download file zip , and use library with example  setVoiceSearch(true || false) dosn't exist .

**Comment by MiguelCatalan** [comment]
This is not posible :/ That method exits from the first release.

**Comment by MiguelCatalan** [comment]
Well if it works for you now with gradle a close the issue. Thanks for the report btw.
