### ISSUE TITLE
Result data from server

### ISSUE THREAD

**Issue by bluedoctorhazan** [MiguelCatalan/MaterialSearchView#61]
I want get data from server, help me!

**Comment by MiguelCatalan** [comment]
This is not related with the library :/ 
There are many ways to do it.
Retrofit/Volley
Asyntask....
http://lmgtfy.com/?q=get+info+from+server+android

**Comment by bluedoctorhazan** [comment]
i aready get data, but i want searchview as arraylist,or SQLite

**Comment by MiguelCatalan** [comment]
http://lmgtfy.com/?q=arraylist+to+String%5B%5D

**Comment by bluedoctorhazan** [comment]
thanks you :)
